/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.HomePage;

/**
 *
 * @author user
 */
public class homePage extends javax.swing.JPanel {

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageProfile = new javax.swing.JButton();
        btnViewInsurance = new javax.swing.JButton();
        btnViewMainRecord = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 500));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setText("Home Page");

        btnManageProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManageProfile.setText("Manage Profile");

        btnViewInsurance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnViewInsurance.setText("View Insurance");

        btnViewMainRecord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnViewMainRecord.setText("View Main Record");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageProfile)
                            .addComponent(btnViewInsurance)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(btnViewMainRecord)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle)
                .addGap(44, 44, 44)
                .addComponent(btnManageProfile)
                .addGap(76, 76, 76)
                .addComponent(btnViewInsurance)
                .addGap(78, 78, 78)
                .addComponent(btnViewMainRecord)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnViewInsurance;
    private javax.swing.JButton btnViewMainRecord;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
