/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Patient;

/**
 *
 * @author user
 */
public class PersonalInfo extends javax.swing.JPanel {

    /**
     * Creates new form PersonalInfo
     */
    public PersonalInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        txtRec1 = new javax.swing.JTextField();
        txtRec2 = new javax.swing.JTextField();
        txtRec3 = new javax.swing.JTextField();
        txtRec4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        updateJButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRec5 = new javax.swing.JTextField();
        txtRec6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtRec7 = new javax.swing.JTextField();
        txtRec8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel16.setText("Weight in pounds");

        txtRec1.setEnabled(false);

        txtRec2.setEnabled(false);

        txtRec3.setEnabled(false);

        txtRec4.setEnabled(false);

        jLabel13.setText("Respiratory rate");

        jLabel14.setText("Heart rate");

        jLabel15.setText("Systolic blood pressure");

        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Move Time (mins)");

        jLabel10.setText("Excercise Time (mins)");

        jLabel11.setText("Total Time (mins)");

        txtRec5.setEnabled(false);
        txtRec5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRec5ActionPerformed(evt);
            }
        });

        txtRec6.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 204));
        jLabel17.setText("View Record Details");

        txtRec7.setEnabled(false);

        txtRec8.setEditable(false);
        txtRec8.setEnabled(false);

        jLabel8.setText("Stand Time (mins)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(213, 213, 213)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addComponent(txtRec1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtRec5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(105, 105, 105)
                            .addComponent(txtRec2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(txtRec6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRec3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRec4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRec7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRec8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(224, 224, 224)
                            .addComponent(saveJButton)
                            .addGap(91, 91, 91)
                            .addComponent(updateJButton))
                        .addComponent(backJButton))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel13))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(txtRec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8))
                        .addComponent(txtRec5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel14))
                        .addComponent(txtRec2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel9))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(txtRec6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel15)
                            .addGap(22, 22, 22)
                            .addComponent(jLabel16))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtRec3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(txtRec4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)
                            .addComponent(jLabel11))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(txtRec7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(txtRec8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(49, 49, 49)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(saveJButton)
                        .addComponent(updateJButton))
                    .addGap(21, 21, 21)
                    .addComponent(backJButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
//        txtRec8.setEnabled(false);
//        if((txtRec1.getText().length()==0)||
//            (txtRec2.getText().length()==0)||
//            (txtRec3.getText().length()==0)||
//            (txtRec4.getText().length()==0)||
//            (txtRec5.getText().length()==0)||
//            (txtRec6.getText().length()==0)||
//            (txtRec7.getText().length()==0))
//        {
//            JOptionPane.showMessageDialog(null, "Alert! Inputs can not be empty! ", "Warning", JOptionPane.WARNING_MESSAGE);
//        } else if((txtRec1.getText().length() != 0) ||
//            (txtRec2.getText().length()!=0) ||
//            (txtRec3.getText().length() != 0)||
//            (txtRec4.getText().length() !=0)||
//            (txtRec5.getText().length() !=0)||
//            (txtRec6.getText().length() !=0)||
//            (txtRec7.getText().length() !=0)) {
//            try{
//
//                //                String patientName = userAccountnameJTextField.getText();
//                float respiratoryRate = Float.parseFloat(txtRec1.getText());
//                float heartRate = Float.parseFloat(txtRec2.getText());
//                float systolicBloodPressure = Float.parseFloat(txtRec3.getText());
//                float weightInPounds = Float.parseFloat(txtRec4.getText());
//                int standTime = Integer.parseInt(txtRec5.getText());
//                int moveTime = Integer.parseInt(txtRec6.getText());
//                int excerciseTime = Integer.parseInt(txtRec7.getText());
//                //int totalTime = Integer.parseInt(txtRec8.getText());
//
//                //Patient patient = patientOrganization.getPatientDirectory().createPtient(userAccount.getName());
//                //userAccount.setPatient(patient);
//                //patient.setPatientName(userAccount.getName());
//                Record record = patient.getRecord();
//                record.setRespiratoryRate(respiratoryRate);
//                record.setHeartRate(heartRate);
//                record.setSystolicBloodPressure(systolicBloodPressure);
//                record.setWeightInPounds(weightInPounds);
//                record.setStandTime(standTime);
//                record.setMoveTime(moveTime);
//                record.setExcerciseTime(excerciseTime);
//                record.setTotalTime();
//                txtRec8.setText(String.valueOf(record.getTotalTime()));
//
//                JOptionPane.showMessageDialog(null, "Create Patient Information Successfully!", "Warning", JOptionPane.WARNING_MESSAGE);
//                //resetFields();
//            }catch(Exception e){
//
//                JOptionPane.showMessageDialog(null, "Alert! Please enter appropriate values! ", "Warning", JOptionPane.WARNING_MESSAGE);
//                saveJButton.setEnabled(false);
//                updateJButton.setEnabled(true);
//            }
//        }
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
//        userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
//        Record record = patient.getRecord();
//        txtRec1.setText(String.valueOf(record.getRespiratoryRate()));
//        txtRec2.setText(String.valueOf(record.getHeartRate()));
//        txtRec3.setText(String.valueOf(record.getSystolicBloodPressure()));
//        txtRec4.setText(String.valueOf(record.getWeightInPounds()));
//        txtRec5.setText(String.valueOf(record.getStandTime()));
//        txtRec6.setText(String.valueOf(record.getMoveTime()));
//        txtRec7.setText(String.valueOf(record.getExcerciseTime()));
//        txtRec8.setText(String.valueOf(record.getTotalTime()));
//
//        txtRec1.setEnabled(true);
//        txtRec2.setEnabled(true);
//        txtRec3.setEnabled(true);
//        txtRec4.setEnabled(true);
//        txtRec5.setEnabled(true);
//        txtRec6.setEnabled(true);
//        txtRec7.setEnabled(true);
//        txtRec8.setEnabled(true);

    }//GEN-LAST:event_updateJButtonActionPerformed

    private void txtRec5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRec5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRec5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton saveJButton;
    private javax.swing.JTextField txtRec1;
    private javax.swing.JTextField txtRec2;
    private javax.swing.JTextField txtRec3;
    private javax.swing.JTextField txtRec4;
    private javax.swing.JTextField txtRec5;
    private javax.swing.JTextField txtRec6;
    private javax.swing.JTextField txtRec7;
    private javax.swing.JTextField txtRec8;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
