/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalAdminRole;

import Business.Employee.Employee;
import Business.Insurance.Insurance;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.RegisterRequest.RegisterRequest;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dongyueli
 */
public class ManageHospitalManagerJPanel extends javax.swing.JPanel {
    private OrganizationDirectory organizationDir;
    private JPanel userProcessContainer;
    /**
     * Creates new form ManageEmployeeJPanel
     */
    public ManageHospitalManagerJPanel(JPanel userProcessContainer,OrganizationDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        
    }
    
    
//    private void populateTable(Insurance insurance){
//        DefaultTableModel model = (DefaultTableModel) ManageHospManagerJTable.getModel();
//        
//        model.setRowCount(0);
//        
//        if (insurance instanceof PatientOrganization) {
//            for (Patient patient : insurance.getPatientDirectory().getPatientList()) {
//                Object[] row = new Object[2];
//                row[0] = patient.getPatientID();
//                row[1] = patient.getPatientName();
//                model.addRow(row);
//
//            }
//        }else{
//            for (Employee employee : insurance.getEmployeeDirectory().getEmployeeList()){
//            Object[] row = new Object[2];
//            row[0] = employee.getEmpId();
//            row[1] = employee.getEmpName();
//            model.addRow(row);
//        }
//        }
//    }
//    
//    private void populateTable(Insurance insurance){
//        DefaultTableModel model = (DefaultTableModel) ManageHospManagerJTable.getModel();   
//        model.setRowCount(0);
//          
//        for(Insurance insurance:ua.getRegisterRequestDirectory().getRegisterRequestList()){
//            Object[] row = new Object[5];
//            row[0] = insurance;
//            row[1] = insurance.getNetwork();
//            row[2] = insurance.getEnterprise();
//            row[3] = insurance.getOrganization();
//            row[4] = insurance.getApproveOrNot();
//             model.addRow(row);
//            
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManageHospManagerJTable = new javax.swing.JTable();
        addEmployeeJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        BackJButton = new javax.swing.JButton();
        RemoveJButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Manage Hospital Manager");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 31, -1, -1));

        ManageHospManagerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ManageHospManagerJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 480, 92));

        addEmployeeJButton.setText("Add Employee");
        addEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeJButtonActionPerformed(evt);
            }
        });
        add(addEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 326, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 361, -1, -1));

        BackJButton.setText("<<Back");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });
        add(BackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        RemoveJButton1.setText("Remove");
        RemoveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveJButton1ActionPerformed(evt);
            }
        });
        add(RemoveJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeJButtonActionPerformed
        // TODO add your handling code here:
        /* 先註解掉避免報錯 Organization organization = (Organization) organizationEmpJComboBox.getSelectedItem();
        String name = nameJTextField.getText();
        if (organization instanceof PatientOrganization) {
            organization.getPatientDirectory().createPtient(name);


        }else{
            organization.getEmployeeDirectory().createEmployee(name);
        }
        
        populateTable(organization);  */
    }//GEN-LAST:event_addEmployeeJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
        // TODO add your handling code here:
    /*先註解掉避免報錯 int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select one row");
        }else{
            RegisterRequest registerRequest = (RegisterRequest) jTable1.getValueAt(selectedRow, 0);
            registerRequest.setApproveOrNot("delince");
            populateTable();
        }*/ 

    }//GEN-LAST:event_BackJButtonActionPerformed

    private void RemoveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveJButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JTable ManageHospManagerJTable;
    private javax.swing.JButton RemoveJButton1;
    private javax.swing.JButton addEmployeeJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
